name: Maven build and tests

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Clean Maven
        run: mvn clean

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Run tests with Maven
        run: mvn -B clean test verify --file pom.xml

  tests-goal-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests goal check
        run: |
          # Place your tests goal check commands here
          # For example, you can run unit tests or any other validation steps
          echo "Tests goal check successful"

  build-with-maven:
    needs: tests-goal-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Clean Maven
        run: mvn clean
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
